#!/bin/bash

###Script after intalation of UBUNTU 18.04 and complements###
## commented after tab is an optional command##
#NOTE: Run this script with 'sudo'
#Versão 0.5

echo -e '
	\n Auto install Bragatte_mode!!!!
	'

## Removing any apt locks ##

sudo rm /var/lib/dpkg/lock-frontend; sudo rm /var/cache/apt/archives/lock ;

## Adding / Confirming 32-bit Architecture ##

sudo dpkg --add-architecture i386 

## Installing basic system utilities ##

cd ~

mkdir /home/$USER/Downloads/Programs

cd /home/$USER/Downloads/Programs

	# sudo apt update -qq # not put any output in the screen

sudo apt install -yy htop gdebi synaptic grsync bleachbit gufw gnome-tweak-tool unity-tweak-tool # install without questions even with errors 

## Updating the repository ##

sudo apt update

## Adding 3rd Party Repositories and Snap Support (Logitech Driver, Lutris, and Nvidia Drivers)##

sudo apt-add-repository -y ppa:graphics-drivers/ppa

sudo apt-add-repository -y ppa:teejee2008/ppa

	#sudo apt-add-repository -y ppa:libratbag-piper/piper-libratbag-git

	#sudo apt-add-repository -y ppa:lutris-team/lutris -y

	#sudo apt-add-repository -y ppa:maarten-baert/simplescreenrecorder

	#sudo apt-add-repository -y ppa:libratbag-piper/piper-libratbag-git

----

## other repositories ##

sudo apt install snapd -y

sudo apt install flatpak -y

wget -nc https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/bionic main'
sudo apt install wine-development
sudo apt install --install-recommends winehq-stable wine-stable wine-stable-i386 wine-stable-amd64 -y #extra wine programs

## Download and install external programs .deb ##

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

wget -c https://dl.4kdownload.com/app/4kvideodownloader_4.9.2-1_amd64.deb

wget -c https://d2t3ff60b2tol4.cloudfront.net/builds/insync_3.0.20.40428-bionic_amd64.deb

## Instalando pacotes .deb baixados na sessão anterior ##

sudo dpkg -i *.deb

## Programas do repositório APT##

sudo apt install -y zsh #alternative option for bash in terminal

sudo apt install -y rpm yum #other formats in linux

sudo apt install -y flameshot #capture and film screen

sudo apt install -y timeshift # backup of our Linux system

sudo apt install -y gnome-sushi #previsualize files pressing space

sudo apt install -y winff #convert vieo formats

sudo apt install -y guvcview #webcam app for streams

sudo apt install -y openssh-server #remotely controlling & transferring

sudo apt install -y audacity #digital audio editor and recording app

sudo apt install -y xpad #sticky note application for GTK

sudo apt install -y python-pip #installs packages

## Gamers repositories and packages

	#sudo apt install -y ratbagd piper #optional config mouse

	# sudo apt install steam-installer steam-devices steam:i386 -y

	# sudo apt install lutris libvulkan1 libvulkan1:i386 -y


## Programs with specific demand

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install albert
##Ref: https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert ##

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt install -y virtualbox #emulate SO
sudo adduser $USER vboxusers

sudo apt install docker.io #containers
sudo groupadd docker
sudo usermod -aG docker $USER 

##Instalando pacotes Flatpak ##

flatpak install flathub com.obsproject.Studio -y

## Instalando pacotes Snap ##

sudo snap install sublime-text --classic #IDE generic

sudo snap install atom --classic #IDE generic other option

sudo snap install pycharm-community --classic #IDE python

sudo snap install notepad-plus-plus #text editor (work with wine)

sudo snap install simplenote #keep notes

sudo snap install inkscape #vector graphics software

sudo snap install blender-tpaw #3D pipeline—modeling, animation, simulation, rendering.

sudo snap install photogimp #patch 'Adobe' for GIMP

sudo snap install slack --classic #standard install comunication app

sudo snap install skype --classic #standard install comunication app

sudo snap install discord #comunication app focus on headset

sudo snap install telegram-desktop #alternative for whatsapp

sudo snap install spotify #digital music service

sudo snap install angstrom # management tool

'''
Option one command line without explanations:
sudo snap install -y sublime-text --classic atom --classic pycharm-community --classic notepad-plus-plus simplenote inkscape blender-tpaw photogimp slack skype discord telegram-desktop spotify angstrom
'''

## Tools for Data Science ##
#Anaconda#

sudo apt install python-setuptools python-dev python-numpy sextractor libusb-dev swig \ libcfitsio-dev:i386 python-gobject-2-dev python-gtk2-dev python-gdl \ python-nose python-epydoc -y

sudo apt install -y libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386 #prequesites for anaconda

wget -c https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O ~/anaconda.sh #edit "Anaconda3-xxx" for updates
sudo bash ~/anaconda.sh -b -u -p
#-b(agree with license)-u(unsubscrive)-p(prefix home)
source /home/$USER/anaconda3/bin/activate
source ~/.bashrc #activate installation
conda config --set auto_activate_base true
#to not activate : conda config --set auto_activate_base false
source /home/$USER/anaconda3/bin/activate
#open new terminal and wirte "anaconda-navigator#
#Create icon for launcher/desktop
#Acess the directory for apps
cd /usr/share/applications/
#!/bin/bash
cat > Anaconda-Navigator.desktop <<EOF
###
#Create or modify the script for launchers - example name for archive:
[Desktop Entry]
 Version=1.0
 Type=Application
 Name=Anaconda-Navigator
 GenericName=Anaconda
 Comment=Scientific Python Development Environment - Python3
 Exec=bash -c 'export PATH="/home/$USER/anaconda3/bin:$PATH" && /home/$USER/anaconda3/bin/anaconda-navigator'
 Categories=Development;Science;IDE;Qt;Education;
 Icon=/home/$USER/anaconda3/lib/python3.7/site-packages/anaconda_navigator/static/images/anaconda.png
 Terminal=false
 StartupNotify=true
 MimeType=text/x-python;

#Attention with paths, name of the images and version of python3.*
###

EOF


## Finishing, updating and cleaning##

sudo apt update && sudo apt upgrade && apt dist-upgrade -y

flatpak update -y

sudo apt autoclean

sudo apt autoremove -y

echo -e '\n All done! Reboot your pc and keep walking!'
