#!/bin/bash

###Script after intalation of UBUNTU 18.04 and complements###
#NOTE: Run this script as ROOT##
#Versão 0.1

echo -e '\n Auto install Bragatte_mode!!!!'

## Removing any apt locks ##

sudo rm /var/lib/dpkg/lock-frontend; sudo rm /var/cache/apt/archives/lock ;

## Adding / Confirming 32-bit Architecture ##

sudo dpkg --add-architecture i386 

## Installing basic system utilities ##

cd ~
# sudo apt update -qq # not put any output in the screen
sudo apt install -yy htop gdebi synaptic grsync bleachbit gufw gnome-tweak-tool unity-tweak-tool # install without questions even with errors 

## Updating the repository ##

sudo apt update

## Adding 3rd Party Repositories and Snap Support (Logitech Driver, Lutris, and Nvidia Drivers)##

sudo apt-add-repository ppa:libratbag-piper/piper-libratbag-git -y

sudo apt-add-repository ppa:lutris-team/lutris -y

sudo apt-add-repository ppa:graphics-drivers/ppa -y

sudo apt-add-repository ppa:maarten-baert/simplescreenrecorder -y

sudo add-apt-repository ppa:libratbag-piper/piper-libratbag-git -y

sudo apt install snapd -y

wget -nc https://dl.winehq.org/wine-builds/winehq.key 

sudo apt-key add winehq.key -y

sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key -O Release.key
sudo apt-key add - < .Release.key
sudo apt update ## Updating the repository after adding new repositories ##
sudo apt install albert

## Download and install external programs ##

mkdir /home/$USER/Downloads/Programs

cd /home/$USER/Downloads/Programs

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

wget -c https://github.com/Automattic/simplenote-electron/releases/download/v1.8.0/Simplenote-linux-1.8.0-amd64.deb 

wget -c https://dl.4kdownload.com/app/4kvideodownloader_4.9.2-1_amd64.deb

wget -c https://d2t3ff60b2tol4.cloudfront.net/builds/insync_3.0.20.40428-bionic_amd64.deb

## Installing .deb Packages Downloaded in the Previous Session ##

sudo dpkg -i *.deb

## APT Repository Programs ##

sudo apt install -yy winff guvcview flameshot dropbox openssh-server zsh audacity gnome-sushi

sudo apt install -yy ratbagd piper #optional config mouse

sudo apt install -yy libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 #prequesites for anaconda

sudo apt install python-setuptools python-dev python-numpy sextractor libusb-dev swig \
libcfitsio-dev:i386 python-gobject-2-dev python-gtk2-dev python-gdl \
python-nose python-epydoc -y

# sudo apt install steam-installer steam-devices steam:i386 -y #optional for games

# sudo apt install lutris libvulkan1 libvulkan1:i386 -y #optional for games

sudo apt install virtualbox virtualbox-ext-pack -yy
sudo adduser $USER vboxusers

sudo apt install docker.io
sudo groupadd docker
sudo usermod -aG docker $USER 

sudo apt-get install --install-recommends winehq-stable wine-stable wine-stable-i386 wine-stable-amd64 -y

sudo apt install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386 -y

##Instalando pacotes Flatpak ##

flatpak install flathub com.obsproject.Studio -y

## Installing Flatpak Packages ##

sudo snap install spotify

sudo snap install slack --classic #standard install

sudo snap install skype --classic

sudo snap install pycharm-community --classic

sudo snap install photogimp

sudo snap install sublime-text --classic

sudo snap install inkscape

sudo snap install blender-tpaw

sudo snap install discord

sudo snap install telegram-desktop

## Tools for Data Science ##

wget -c https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O ~/anaconda.sh #edit "Anaconda3-xxx" for updates
bash ~/anaconda.sh -b -p $HOME/anaconda3 #-b agree with license terms

wget -c https://github.com/insilichem/pychimera/archive/master.zip
unzip pychimera*.zip
cd pychimera-master
python setup.py install

## Finishing, updating and cleaning ##

sudo apt update && sudo apt dist-upgrade -y

flatpak update -y

sudo apt autoclean

sudo apt autoremove -y

echo -e '\n All done! Reboot your pc and keep walking!'
