#!/bin/bash

###Script after intalation of UBUNTU 18.04 and complements###
## commented after tab is an optional command##
#NOTE: Run this script as ROOT#
#Versão 0.3

echo -e '
	\n Auto install Bragatte_mode!!!!
	'

## Removing any apt locks ##

sudo rm /var/lib/dpkg/lock-frontend; sudo rm /var/cache/apt/archives/lock ;

## Adding / Confirming 32-bit Architecture ##

sudo dpkg --add-architecture i386 

## Installing basic system utilities ##

cd ~

mkdir /home/$USER/Downloads/Programs

cd /home/$USER/Downloads/Programs

	# sudo apt update -qq # not put any output in the screen

sudo apt install -yy htop gdebi synaptic grsync bleachbit gufw gnome-tweak-tool unity-tweak-tool # install without questions even with errors 

## Updating the repository ##

sudo apt update

## Adding 3rd Party Repositories and Snap Support (Logitech Driver, Lutris, and Nvidia Drivers)##

sudo apt-add-repository ppa:graphics-drivers/ppa -y

	#sudo apt-add-repository ppa:libratbag-piper/piper-libratbag-git -y

	#sudo apt-add-repository ppa:lutris-team/lutris -y

	#sudo apt-add-repository ppa:maarten-baert/simplescreenrecorder -y

	#sudo apt-add-repository ppa:libratbag-piper/piper-libratbag-git -y

	#sudo apt-add-repository ppa:...timeshift
----

## other repositories ##

sudo apt install snapd -y

wget -nc https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/bionic main'
sudo apt install wine-development
sudo apt install wine-stable

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.10/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
wget -nc https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt update
sudo apt install albert

## Updating the repository after adding new repositories ##


## Download and install external programs ##

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# wget -c https://github.com/Automattic/simplenote-electron/releases/download/v1.8.0/Simplenote-linux-1.8.0-amd64.deb 

wget -c https://dl.4kdownload.com/app/4kvideodownloader_4.9.2-1_amd64.deb

# wget -c https://d2t3ff60b2tol4.cloudfront.net/builds/insync_3.0.20.40428-bionic_amd64.deb

## Instalando pacotes .deb baixados na sessão anterior ##

sudo dpkg -i *.deb

## Programas do repositório APT##

sudo apt install -y zsh #alternative option for bash in terminal

sudo apt install -y flameshot #capture and film screen

sudo apt install -y gnome-sushi #previsualize files pressing space

sudo apt install -y winff #convert vieo formats

sudo apt install -y guvcview #webcam app for streams

sudo apt install -y openssh-server #remotely controlling & transferring

sudo apt install -y audacity #digital audio editor and recording app

	#sudo apt install -y ratbagd piper #optional config mouse

sudo apt install -y libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 #prequesites for anaconda

sudo apt install python-setuptools python-dev python-numpy sextractor libusb-dev swig \
libcfitsio-dev:i386 python-gobject-2-dev python-gtk2-dev python-gdl \
python-nose python-epydoc -y

	# sudo apt install steam-installer steam-devices steam:i386 -y #optional for games

	# sudo apt install lutris libvulkan1 libvulkan1:i386 -y #optional for games

sudo apt install virtualbox virtualbox-ext-pack -license accept	#emulate SO
sudo adduser $USER vboxusers

sudo apt install docker.io #containers
sudo groupadd docker
sudo usermod -aG docker $USER 

sudo apt-get install --install-recommends winehq-stable wine-stable wine-stable-i386 wine-stable-amd64 -y #adapt win programs

sudo apt install libgnutls30:i386 libldap-2.4-2:i386 libgpg-error0:i386 libxml2:i386 libasound2-plugins:i386 libsdl2-2.0-0:i386 libfreetype6:i386 libdbus-1-3:i386 libsqlite3-0:i386 -y

##Instalando pacotes Flatpak ##

flatpak install flathub com.obsproject.Studio -y

## Instalando pacotes Snap ##

sudo snap install sublime-text --classic #IDE generic

sudo snap install pycharm-community --classic #IDE python

sudo snap install inkscape #vector graphics software

sudo snap install blender-tpaw #3D pipeline—modeling, animation, simulation, rendering.

sudo snap install photogimp #patch 'Adobe' for GIMP

sudo snap install slack --classic #standard install comunication app

sudo snap install skype --classic #standard install comunication app

sudo snap install discord #comunication app focus on headset

sudo snap install telegram-desktop #alternative for whatsapp

sudo snap install spotify #digital music service

## Tools for Data Science ##

wget -c https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O ~/anaconda.sh #edit "Anaconda3-xxx" for updates
bash ~/anaconda.sh -b -p $HOME/anaconda3 #-b agree with license terms

wget -c https://github.com/insilichem/pychimera/archive/master.zip
unzip pychimera*.zip
cd pychimera-master
python setup.py install

## Finishing, updating and cleaning##

sudo apt update && sudo apt dist-upgrade -y

flatpak update -y

sudo apt autoclean

sudo apt autoremove -y

echo -e '\n All done! Reboot your pc and keep walking!'
